data:
  root: "./datasets/GOPRO"
  train_dir: "train"
  test_dir: "test"
  input_dir: "blur"
  target_dir: "sharp"  
  image_size: 256
  batch_size: 4
  num_workers: 4
  max_len: 1  

model:
  in_ch: 3
  out_ch: 3
  base_ch: 36
  depths: [2, 3, 3, 4]
  num_refine_blocks: 3
  norm_in: false
  final_activation: null

  hs2m_cfg:
    m: 128
    r: 8
    token_dim: 64
    chunk_len: 256

  rask_cfg:
    K: 4
    region_size: 16
    hidden: 64
    use_sharpen: true
  sssm_cfg:
    use_ln: true

  loss_weights:
    rec: 1.0
    grad: 1.0
    freq: 1.0
    e: 1.0
  use_global_token: false
  global_token_dim: 64
  

training:
  model_dir: "./outputs/GOPRO/"
  epochs: 800
  batch_size: 4
  learning_rate: 0.0003
  weight_decay: 0.0001
  warmup_epochs: 5
  save_freq: 10
  eval_freq: 5
  print_freq: 100
  
  optimization:
    optimizer:
      name: "AdamW"
      lr: 0.0003
      weight_decay: 0.0001
      betas: [0.9, 0.999]
    
    scheduler:
      name: "CosineAnnealingLR"
      T_max: 800
      eta_min: 0.00001

evaluation:
  metrics: ["psnr", "ssim", "lpips"]
  save_images: true
  save_high_res: false 